# Generated by Django 5.0.6 on 2024-07-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pregnancy_status',
            field=models.BooleanField(default=False),
        ),
    ]
