# Generated by Django 5.0.6 on 2024-07-25 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_user_age_user_gender_user_pregnancy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pregnancy_status',
        ),
    ]
