# Generated by Django 5.0.6 on 2024-08-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_user_calcium_necessary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='calcium_necessary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
