# Generated by Django 5.0.6 on 2024-08-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_user_age_remove_user_calcium_necessary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(default='', max_length=100)),
                ('memo', models.TextField(default='memo', max_length=200)),
                ('expense', models.IntegerField(default=0)),
            ],
        ),
    ]
