# Generated by Django 5.0.6 on 2024-08-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='categories',
            field=models.CharField(choices=[('Utility', 'Utility'), ('Food', 'Food'), ('Gas', 'Gas'), ('Mortage/Rent', 'Mortage/Rent'), ('Transportation', 'Transportation'), ('Subscriptions', 'Subscriptions'), ('Healthcare', 'Healthcare'), ('Personal Expenses', 'Personal Expenses'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
