# Generated by Django 5.0.6 on 2024-08-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rename_categories_record_category_record_next_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
