# Generated by Django 5.0.6 on 2024-08-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_record_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.TextField(default='', max_length=200),
        ),
    ]
