# Generated by Django 5.0.6 on 2024-08-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_record_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='next',
        ),
        migrations.RemoveField(
            model_name='record',
            name='prev',
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('Utility', 'Utility'), ('Food', 'Food'), ('Gas', 'Gas'), ('Mortgage/Rent', 'Mortgage/Rent'), ('Transportation', 'Transportation'), ('Subscriptions', 'Subscriptions'), ('Healthcare', 'Healthcare'), ('Personal Expenses', 'Personal Expenses'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
